### ISSUE TITLE
Rebuild PyTorch and ONNX Serve Docker Images

### ISSUE THREAD

**Issue by huangyz0918** [cap-ntu/ML-Model-CI#132]
For #129 this fix, we should update the docker images in the Docker Hub

## Fixed CUDA Version 

We should also fix the CUDA version in those two docker images. Currently our benchmarking uses CUDA version `10.0.130` in TensorFlow/Serving and TensorRT Server, the ONNX and PyTorch serve Docker images should keep the same. 

You can `FROM` a base [`10.0-cudnn7-tensorrt7-devel-ubuntu16.04 (cuda 10.0.130, nccl 2.6.4, cudnn 7.6.5.32 tensorrt 7.0.0.11)`](https://hub.docker.com/r/vistart/cuda) image to build the image.

**Comment by YuanmingLeee** [comment]
Updated new docker images for PyTorch Serving and ONNX Serving:
Pull docker images with CUDA version 10.0 by:
PyTorch:
```shell script
docker pull mlmodelci/pytorch-serving:10.0
```
ONNX:
```shell script
docker pull mlmodelci/pytorch-serving:10.0
```

You can check if the new builds work for your benchmarking @huangyz0918
