### ISSUE TITLE
Paper Website Update Required

### ISSUE THREAD

**Issue by huangyz0918** [cap-ntu/ML-Model-CI#135]
The [paper website](https://cap-ntu.github.io/mlmodelci_mm_demo/) need to improve before the conference. 

- Links in the top (e.g., code, paper, slides) should be correct.
- Model List to switch the profiling results, currently only supports ResNet50. For JSON format profiling data, can turn to @huangyz0918.

**Comment by YuanmingLeee** [comment]
Links are updated by commit https://github.com/cap-ntu/mlmodelci_mm_demo/commit/1343aae6d57613bf68cbf242be809ad678de1766
