### ISSUE TITLE
start script run error

### ISSUE THREAD

**Issue by univerone** [cap-ntu/ML-Model-CI#146]
#### Software and Hardware Versions 
- ModelCI v1.x.x
- CUDA Version vx.x.x
- GPU device used...

#### Problem description

There is no `install.pull_docker_images.sh` and `install.start_service.sh` under `scripts` subfolder
```
Generating gRPC code...Pulling Docker images...bash: scripts/install.pull_docker_images.sh: 没有那个文件或目录
FAIL
Starting services...bash: scripts/install.start_service.sh: 没有那个文件或目录
FAIL
```

#### Steps to Reproduce the Problem
```bash
bash scripts/install.sh
```

#### Expected Behavior

run without error and start the service

#### Other Information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

add relevant bash script file or modify `bash/install.sh`

**Comment by YuanmingLeee** [comment]
Currently you can ignore the error and start ModelCI service directly:
```shell script
import modelci.cli

modelci.cli.start()

# with GPU enabled
# modelci.cli.start(gpu=True)
```

Try if this works.

**Comment by univerone** [comment]
> Currently you can ignore the error and start ModelCI service directly:
> 
> ```shell
> import modelci.cli
> 
> modelci.cli.start()
> 
> # with GPU enabled
> # modelci.cli.start(gpu=True)
> ```
> 
> Try if this works.

Thanks!  I just came across  module import error as following: 

```python
>>> import modelci.cli
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/project/github/ML-Model-CI/modelci/cli/__init__.py", line 53, in <module>
    cli.add_command(modelci.cli.model_cli.commands)
AttributeError: module 'modelci' has no attribute 'cli'
```
And the error gone if I change `model_cli` import code in  `modelci/cli/__init__.py`

```python
from modelci.cli import model_cli
cli.add_command(model_cli.commands)
cli.add_command(model_cli.models)
```
I wonder if this is a common error or just a one-time error due to my incorrect settings

**Comment by YuanmingLeee** [comment]
I see, thx for reporting a bug!
