### ISSUE TITLE
Add CI tests for converter with larger converage

### ISSUE THREAD

**Issue by YuanmingLeee** [cap-ntu/ML-Model-CI#151]
#### Problem description

This is a request for a new feature on CI testing.

We would like to have a larger coverage for converter CI tests.
You may refer here https://github.com/microsoft/hummingbird/tree/master/tests for traditional ML -> {PyTorch, ONNX} first.

#### Other Information 
Roadmap (you may change this as you prefer)

- [ ] pytest -> PyUnit test
- [ ] XGBoost test
- [ ] LightGBM test
- [ ] sklearn test
- [ ] Keras test
...

@univerone

**Comment by univerone** [comment]
I'll get started on it, let's discuss the detail later on
