### ISSUE TITLE
Failed to start with GPU enabled

### ISSUE THREAD

**Issue by univerone** [cap-ntu/ML-Model-CI#153]
#### Software and Hardware Versions 
ModelCI v1.x.x,
CUDA Version v10.2 
GPU device used: True

#### Problem description

Failed to started the program with gpu option

```
Traceback (most recent call last):
  File "~/project/github/ML-Model-CI/test.py", line 4, in <module>
    modelci.cli.start(gpu=True)
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/click/core.py", line 698, in make_context
    ctx = Context(self, info_name=info_name, parent=parent, **extra)
TypeError: __init__() got an unexpected keyword argument 'gpu'
```

#### Steps to Reproduce the Problem

```python
import modelci.cli
modelci.cli.start(gpu=True)
```

#### Expected Behavior

the program started without error

#### Other Information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

after commenting the 25th line of `modelci/cli/__init__.py`, the error disappeared

https://github.com/cap-ntu/ML-Model-CI/blob/ca81463f7b881dbdcdb15ad6dd47a39f7c0a0643/modelci/cli/__init__.py#L25-L27

**Comment by univerone** [comment]
Maybe we could refer to this  for a solution: https://stackoverflow.com/questions/37041126/unexpected-keyword-argument-in-python-click

**Comment by YuanmingLeee** [comment]
An urgent but not elegant solution:
```shell script
python modelci/cli/__init__.py start --gpu
```

May try using cli command when #140 merged

**Comment by univerone** [comment]
> An urgent but not elegant solution:
> 
> ```shell
> python modelci/cli/__init__.py start --gpu
> ```
> 
> May try using cli command when #140 merged

There is still error:

```
Traceback (most recent call last):
  File "modelci/cli/__init__.py", line 10, in <module>
    from modelci.app import (start as app_start, stop as app_stop)
ModuleNotFoundError: No module named 'modelci'
``

**Comment by YuanmingLeee** [comment]
Every time you start a new shell, please update the environment variables before running scripts:
```shell script
# start a new shell

# update env
source scripts/setup_env.sh

# run your python command here
python ...
```

**Comment by univerone** [comment]
> PYTHONPATH=${PWD}

It's kind of strange, if I execute the following 

```shell
PYTHONPATH=$PWD python modelci/cli/__init__.py
```
The error disappears
but if I execute 

```shell
PYTHONPATH=$PWD && python modelci/cli/__init__.py
```
or

```shell
PYTHONPATH=$PWD
python modelci/cli/__init__.py
```
The module import error comes out again

**Comment by YuanmingLeee** [comment]
try `export PYTHONPTH=$PWD`

**Comment by univerone** [comment]
> try `export PYTHONPTH=$PWD`

Thanks! This did help

**Comment by HuaizhengZhang** [comment]
after the new pip installation feature, this issue should be fixed
