### ISSUE TITLE
docker pull mlmodelci/mlmodelci

### ISSUE THREAD

**Issue by crane136** [cap-ntu/ML-Model-CI#228]
#### Software and Hardware Versions 
ModelCI v1.x.x, CUDA Version vx.x.x, GPU device used...

#### Problem description
docker pull mlmodelci/mlmodelci

How to start the docker ? Is there any docs?
(I have got the docker image,)

#### Other Information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by crane136** [comment]
I want use the image to start mlmodelci service

**Comment by HuaizhengZhang** [comment]
> I want use the image to start mlmodelci service

Thanks for using our modelci.

Currently, the docker image is mainly for system development, so you need to manually install the system in the docker env.

**Comment by HuaizhengZhang** [comment]
We are working on refactoring the system since we get some feedback from users.

The current document is out of date. We will update it soon and notify you with an email

**Comment by crane136** [comment]
Thanks

**Comment by crane136** [comment]
Is there a docker-compose file or a kubernetes yaml that install mlmodelci ? 在 2021年2月23日，下午4:06，Huaizheng <notifications@github.com> 写道：We are working on refactoring the system since we get some feedback from users.The current document is out of date. We will update it soon and notify you with an email—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by HuaizhengZhang** [comment]
https://github.com/cap-ntu/ML-Model-CI/tree/master/modelci/hub/deployer/k8s

This is provided by our outside collaborators who have a k8s cluster.

I have not tested this by myself. If you meet any issues, please tell us. We will try to fix it.

**Comment by crane136** [comment]
Thanks

**Comment by crane136** [comment]
Is Mlmodelci only support ubuntu  ? (What should I do  If I want install on Centos )

**Comment by HuaizhengZhang** [comment]
Yes. Now we only test is on ubuntu.
We have no plan to support CentOS in the near future as we are a very small research team currently.

We hope to support macOS in the next version.

**Comment by huangyz0918** [comment]
> Is Mlmodelci only support ubuntu  ? (What should I do  If I want install on Centos )
 If you have Docker or Python, you can run the developing and most functions. We will not rebuild the system on CentOS.

Thanks for your feedback, we are opening to your issues and suggestions.
