### ISSUE TITLE
无法正常安装使用

### ISSUE THREAD

**Issue by AlpacaKnight** [cap-ntu/ML-Model-CI#236]
系统环境：服务器，ubuntu 18.04，不使用CUDA

我尝试使用readme中提供的方法分别使用docker，pip的方式安装了。
pull docker镜像之后，可以正常的启动镜像，但无法执行 modelci service init 命令；
pip方式安装后一样，均无法执行modelci。
不知道通过何种方式访问readme中描述的web界面，执行from modelci.hub.manager import 的相关操作也无法使用。

按照文档中的安装与使用说明执行相关操作后无法使用项目描述中已有的功能，能否提供更为详细可用的文档，或是否有交流群

**Comment by HuaizhengZhang** [comment]
不好意思，做了一次大的改版，文档更新和测试没有跟上

这周我们尽快做个更新

**Comment by AlpacaKnight** [comment]
您好，请问文档已经更新了么，我看readme里并没有变化

**Comment by HuaizhengZhang** [comment]
Hi, you may refer to our latest two merged PRs to run the system.
