### ISSUE TITLE
UniTest for CLI and API

### ISSUE THREAD

**Issue by YuanmingLeee** [cap-ntu/ML-Model-CI#244]
* Write UniTest for `models/` RESTful API.
* Write UniTest for `modelhub` CLI

_Originally posted by @YuanmingLeee in https://github.com/cap-ntu/ML-Model-CI/pull/240#discussion_r592433645_

Possible reference:
Save a model weights file in GitHub Action: https://github.com/marketplace/actions/get-file

**Comment by univerone** [comment]
This might be helpful: https://typer.tiangolo.com/tutorial/testing/
