### ISSUE TITLE
Fixed the issues with profiler

### ISSUE THREAD

**Issue by huangyz0918** [cap-ntu/ML-Model-CI#247]
Currently we have a profiling module in modelci. It cannot be connected with the frontend and CLI through the database. The target in the issue is to,

- Get familiar with the profiler in this project. 
- Run profiler module, and debug it with the local database.
- Fix the issues with connecting to the top level controller. The objective is to call the profiling function using controller successfully.
- Fix the issues with calling profiling functions in the CLI. The objective is to run the profiling functions using CLI commands successfully.
- Fix the issues with calling profiling functions using the web interface. The objective is to run the functions using web interface successfully.
- add unit test

**Comment by Lionjump0723** [comment]
It seems that current api of register_model doesn't match with the register.md as well as modelci/hub/init_data.py
So after I convert a model from pytorch to torchscript, how can I register the new model conveniently?

**Comment by HuaizhengZhang** [comment]
please refer to Wiki

**Comment by Lionjump0723** [comment]
The wiki seems to be incomplete about apis, however I've solved it by editing yaml file and use the register_model_from_yaml api. 
Now new question arises. When I try to run profiler.diagnose, here comes an error about grpc

```
Traceback (most recent call last):
  File "playground_convert.py", line 38, in <module>
    profiler.diagnose(device='cpu')
  File "/home/cai/ML-Model-CI/modelci/hub/profiler.py", line 83, in diagnose
    result = self.inspector.run_model(server_name=self.server_name, device=device)
  File "/home/cai/ML-Model-CI/modelci/metrics/benchmark/metric.py", line 110, in run_model
    self.start_infer_with_time(batch)
  File "/home/cai/ML-Model-CI/modelci/metrics/benchmark/metric.py", line 184, in start_infer_with_time
    self.infer(request)
  File "/home/cai/ML-Model-CI/modelci/hub/client/torch_client.py", line 64, in infer
    self.stub.Infer(request)
  File "/home/cai/anaconda3/envs/modelci/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/cai/anaconda3/envs/modelci/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1617281238.438142526","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4090,"referenced_errors":[{"created":"@1617281238.438140603","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}"
>
```
And below is my code. 
```
rom modelci.hub.client.torch_client import CVTorchClient
from modelci.hub.profiler import Profiler
from modelci.hub.deployer.dispatcher import serve
test_data_item = np.zeros((16,16,3), dtype=np.uint8)
batch_num = 100
batch_size = 32

# Obtain model info from `retrieve_models` API.
model_info = retrieve_model()[0]

# create a client
torch_client = CVTorchClient(test_data_item, model_info, batch_num, batch_size, asynchronous=False)

# init the profiler
container = serve(model_info.saved_path, name = 'emm')

profiler = Profiler(model_info=model_info, server_name=container.name, inspector=torch_client)

# start profiling model
profiler.diagnose(device='cpu')
```

I don't understand the meaning of server_name parameter in the diagnose function. Is it just the mlmodelci/pytorch-serving:latest, or the new docker image built in modelci/hub/deployer/pytorch, or anything else? Thanks for your reply.
