### ISSUE TITLE
Improve convert function

### ISSUE THREAD

**Issue by univerone** [cap-ntu/ML-Model-CI#248]
Try to read ONNX and TensorRT documents, add more conversion functions including but not limited to 
- [ ] Add tensorflow model to ONNX format conversion function
- [ ] Add tensorflow saved model to tensorRT format conversion function( Note: This task has been changed)
~~- [ ] add keras to ONNX~~
- [ ] Add test for these functions
- [ ] Complete convert CLI `modelci modelhub convert`(read our wiki)

Reference: 

- https://github.com/cap-ntu/ML-Model-CI/tree/master/tests
- https://github.com/cap-ntu/ML-Model-CI/tree/master/modelci/hub/converter
- https://github.com/cap-ntu/ML-Model-CI/blob/master/modelci/hub/manager.py#L152-L195

**Comment by STALLAAAA** [comment]
what should the tf2onnx model return? a session for inference or a path where the .onnx  is saved?

**Comment by STALLAAAA** [comment]
i cant find any available model in savedmodel format for tensorflow unit testing thus i trained one myself. Where should i put this file since i dont find  any other contributer upload a local model file?

**Comment by univerone** [comment]
> i cant find any available model in savedmodel format for tensorflow unit testing thus i trained one myself. Where should i put this file since i dont find any other contributer upload a local model file?

Better load a pretrained tf model(such as from `tf.keras.applications`) and save it as savedmodel format

**Comment by univerone** [comment]
> what should the tf2onnx model return? a session for inference or a path where the .onnx is saved?

Please refer to https://github.com/cap-ntu/ML-Model-CI/blob/master/modelci/hub/converter/to_onnx.py , and follow the same output format

**Comment by STALLAAAA** [comment]
I have uploaded codes about tf2onnx and tf2trt functions as well as unit testing for them. For now, all of them have run well on my machine. If there are any issue when you checked it, please inform me of the error information and i will try to fix it. Thanks!

**Comment by univerone** [comment]
> I have uploaded codes about tf2onnx and tf2trt functions as well as unit testing for them. For now, all of them have run well on my machine. If there are any issue when you checked it, please inform me of the error information and i will try to fix it. Thanks!

@STALLAAAA Don't forget to make a pull request to submit your code

**Comment by STALLAAAA** [comment]
I made a pull request but the automatic check blocked my merge because of the environment lacking of tensorrt. How should i fix this?

**Comment by STALLAAAA** [comment]
I have made a pull request for convert CLI, the converting functions(tf2onnx,tf2trt) and a test for tf2onnx. The CLI currently only implements 3 functions. If you approve with the design of convert CLI, I will continue on it and have more functions implemented.
My solution about the test for tf2trt requires pycuda but  you do not need this lib, so I have to find another way to do it. The problem is that nvidia official documents uses pycuda as the example of trt inferring. If I want to do  the inferring  without  pycuda, I need to tend to other learning resources about tensorrt.  Thus, it would be a great help if you could provide some advice about this. Thanks!

**Comment by HuaizhengZhang** [comment]
@STALLAAAA 
https://github.com/NVIDIA/sampleQAT#step-1-quantization-aware-training

Have you tried this? If not you may learn the tutorial and borrow some ideas from it.

**Comment by STALLAAAA** [comment]
> @STALLAAAA
> https://github.com/NVIDIA/sampleQAT#step-1-quantization-aware-training
> 
> Have you tried this? If not you may learn the tutorial and borrow some ideas from it.

It uses PYCUDA too. If we do need to perform test on trt inference, I still recommend to use PYCUDA  anyway since it seems to be the most accepted method in community.
