### ISSUE TITLE
Failed tests/test_modelhub_cli.py 

### ISSUE THREAD

**Issue by STALLAAAA** [cap-ntu/ML-Model-CI#281]
My environment shows as below:
`platform linux -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1`
`rootdir: /home/stella/.local/share/Trash/files/ML-Model-CI/tests, configfile: pytest.ini`
`plugins: typeguard-2.11.1`
`collected 6 items      `                                                                                                                 

`tests/test_modelhub_cli.py FFFFFF                                                                                                 [100%]`
Is it my environment problem or an unfixed issue?

**Comment by YuanmingLeee** [comment]
Is there any other log? We cannot tell without error information.

**Comment by STALLAAAA** [comment]
> Is there any other log? We cannot tell without error information.
a example of test_delete failure is as below:
   ` def `test_delete():`
    `    with requests.get(f'{app_settings.api_v1_prefix}/model/') as r:`
         `   model_list = r.json()`
`>       model_id = model_list[0]["id"]`
`E       IndexError: list index out of range`

`tests/test_modelhub_cli.py:56: IndexError`

**Comment by STALLAAAA** [comment]
I shift my environment to

> ============================================= test session starts ==============================================
platform linux -- Python 3.7.7, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/stella/PycharmProjects/ML-Model-CI/tests, configfile: pytest.ini
plugins: env-0.6.2


`
