### ISSUE TITLE
onnxruntime how to to specify a GPU device?

### ISSUE THREAD

**Issue by huangyz0918** [cap-ntu/ML-Model-CI#37]
I'm afraid this is an issue that we cannot specify a GPU device to test. Currently, we limited the GPU usage by setting flag `os.environ["CUDA_VISIBLE_DEVICES"]="0"` in the server, but I think that's not a good idea, since CPU will join serving and I didn't see any task while typing `nvidia-smi`, which means there are no binding tasks in the GPU.

reference
https://github.com/Microsoft/onnxruntime/issues/331

**Comment by fefe982** [comment]
check here:

https://www.onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#python

```
import onnxruntime as ort

model_path = '<path to model>'

providers = [
    ('CUDAExecutionProvider', {
        'device_id': 0,
    }),
    'CPUExecutionProvider',
]

session = ort.InferenceSession(model_path, providers=providers)
```

**Comment by JarvisKevin** [comment]
ort.InferenceSession(onnx_dir, providers=['CUDAExecutionProvider'], provider_options=[{'device_id': 2}])
